version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: sql_container
    environment:
      MYSQL_ROOT_PASSWORD: Pass123
      MYSQL_DATABASE: Chatapp_Db
      MYSQL_USER: Profileuser
      MYSQL_PASSWORD: Pass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
